### ISSUE TITLE
Alerting causes panic with some providers

### ISSUE THREAD

**Issue by tiwood** [TwinProduction/gatus#146]
Hello 👋️

I'm getting the following error as soon as my `PagerDuty` alert triggers:

```text
2021-07-29T14:33:28.046702739Z 2021/07/29 14:33:28 [watchdog][handleAlertsToTrigger] Sending pagerduty serviceAlert because serviceAlert for service=DNS lookup of Azure-hosted zones/records with description='healthcheck failed' has been TRIGGERED
2021-07-29T14:33:28.050785839Z panic: runtime error: invalid memory address or nil pointer dereference
2021-07-29T14:33:28.052090439Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x724706]
2021-07-29T14:33:28.052107639Z 
2021-07-29T14:33:28.052113339Z goroutine 24 [running]:
2021-07-29T14:33:28.053730239Z github.com/TwinProduction/gatus/client.(*Config).GetHTTPClient(0x0, 0xc00003fd70)
2021-07-29T14:33:28.054827438Z 	/app/client/config.go:51 +0x26
2021-07-29T14:33:28.054843638Z github.com/TwinProduction/gatus/client.GetHTTPClient(...)
2021-07-29T14:33:28.055620538Z 	/app/client/client.go:19
2021-07-29T14:33:28.061828638Z github.com/TwinProduction/gatus/alerting/provider/custom.(*AlertProvider).Send(0xc000472de0, 0xc00003fd70, 0x28, 0xc000042e28, 0x12, 0xc000472d00, 0x0, 0x0, 0xc0002fea50, 0x9, ...)
2021-07-29T14:33:28.061854938Z 	/app/alerting/provider/custom/custom.go:118 +0xd6
2021-07-29T14:33:28.061861638Z github.com/TwinProduction/gatus/watchdog.handleAlertsToTrigger(0xc0000dd080, 0xc0003b9800, 0xc00039a0c0, 0x0)
2021-07-29T14:33:28.061879438Z 	/app/watchdog/alerting.go:47 +0x525
2021-07-29T14:33:28.061893038Z github.com/TwinProduction/gatus/watchdog.HandleAlerting(0xc0000dd080, 0xc0003b9800, 0xc00039a0c0, 0x0)
2021-07-29T14:33:28.061897538Z 	/app/watchdog/alerting.go:20 +0x7e
2021-07-29T14:33:28.061901138Z github.com/TwinProduction/gatus/watchdog.execute(0xc0000dd080, 0xc00039a0c0, 0x1)
2021-07-29T14:33:28.061904738Z 	/app/watchdog/watchdog.go:73 +0x251
2021-07-29T14:33:28.061908238Z github.com/TwinProduction/gatus/watchdog.monitor(0xc0000dd080, 0xc00039a0c0, 0xc000000001, 0x1a15510, 0xc00039a340)
2021-07-29T14:33:28.061911938Z 	/app/watchdog/watchdog.go:46 +0xb7
2021-07-29T14:33:28.061915338Z created by github.com/TwinProduction/gatus/watchdog.Monitor
2021-07-29T14:33:28.061918938Z 	/app/watchdog/watchdog.go:31 +0x110
```

My configuration is as follows:

```yaml
alerting:
  pagerduty:
    integration-key: "${PAGERDUTY_INTEGRATION_KEY}"

services:
  - name: DNS lookup of Azure-hosted zones/records
    group: core/dns
    url: "10.250.200.155"
    interval: 1m
    dns:
      query-name: "health.dns.service"
      query-type: "A"
    conditions:
      - "[BODY] == 1.1.1.1"
      - "[DNS_RCODE] == NOERROR"
    alerts:
      - type: pagerduty
        enabled: true
        failure-threshold: 3
        success-threshold: 5
        send-on-resolved: true
        description: "healthcheck failed"
```

I'm using the latest version and I've already checked if the variable expansion is the issue, which seems not the case.

**Comment by TwinProduction** [comment]
@tiwood Thanks for letting me know. This is definitely because of the change I made yesterday in #126, I'll push a fix shortly.

**Comment by TwinProduction** [comment]
@tiwood Can you try now and let me know?
I've tested it on my end and it should work, but just to make sure.

**Comment by tiwood** [comment]
Thanks @TwinProduction, I've tested with the latest version and it works like a charm!
Thanks for building this great tool

**Comment by TwinProduction** [comment]
@tiwood Thanks for getting back to me so quickly, I appreciate it :)

And only again, sorry for the inconvenience.
